# Project information
site_name: Test ghpages
site_author: 'Gab'
site_url:
remote_branch: gh-pages
edit_uri: 'tree/main/docs/'

# Repository
repo_name: 'Test GHPAGES'
repo_url: https://github.com/gabrielemariotti/test_ghpages


theme:
  name: 'material'

markdown_extensions:
  - codehilite:
  - pymdownx.superfences
  - admonition

nav:
    - Getting started: index.md
